# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
pool:
  name: default
  demands:
   - agent.name -equals incubation-lab-


variables:
- group: incubation
  
stages:
  - stage: Build_Push_Health_alert_receiver
    displayName: Build_Push_Health_alert_receiver
    jobs:
      - job: publishfiles
        steps:
        - task: CopyFiles@2
          inputs:
            SourceFolder: 'docker'
            Contents: '**'
            TargetFolder: '$(build.artifactstagingdirectory)'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'
        - task: DownloadBuildArtifacts@0
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: 'drop'
            downloadPath: '$(System.ArtifactsDirectory)'
                
        - task: Docker@0
          displayName: 'Build an image'
          inputs:
            azureSubscription: $(sercon)
            azureContainerRegistry: '{"loginServer":"$(name)$(env)acr.azurecr.io", "id" : "/subscriptions/$(sub_id)/resourceGroups/$(name)/providers/Microsoft.ContainerRegistry/registries/$(name)$(env)acr"}'
            dockerFile: '$(System.ArtifactsDirectory)/drop/Dockerfile'
            imageName: 'mediawiki'
            includeLatestTag: true
            workingDirectory: '$(System.ArtifactsDirectory)/drop'

        - task: Docker@0
          displayName: 'Push an image'
          inputs:
            azureSubscription: $(sercon)
            azureContainerRegistry: '{"loginServer":"$(name)$(env)acr.azurecr.io", "id" : "/subscriptions/$(sub_id)/resourceGroups/$(name)/providers/Microsoft.ContainerRegistry/registries/$(name)$(env)acr"}'
            action: 'Push an image'
            imageName: 'mediawiki'
            includeLatestTag: true
            workingDirectory: '$(System.ArtifactsDirectory)/drop'