apiVersion: v1
kind: Service
metadata:
  name: {{ template "wikimedia.fullname" . }}-mariadb-service
  namespace: {{ .Release.namespace }}
  labels:
    app: {{ template "wikimedia.name" . }}-db
    type: database
spec:
  selector:
    app: {{ template "wikimedia.name" . }}-db
    type: database
  ports:
  - port: 3306
    targetPort: db-port
  type: ClusterIP 