apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "wikimedia.fullname" . }}-physical-volume
  namespace: {{ .Release.namespace }}
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.persistentVolume.storage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "wikimedia.fullname" . }}-mariadb-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistentVolume.storage }}
