apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: {{ .Release.namespace }}
data:
  dbname: {{ .Values.secrets.dbname }}
  db-password: {{ .Values.secrets.dbpassword }}
  dbrootpassword: {{ .Values.secrets.dbrootpassword }}
  db-username: {{ .Values.secrets.dbuser }}

