apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: test-external-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: secret-store

  target:
    name: db-secret

  data:
  # name of the SECRET in the Azure KV (no prefix is by default a SECRET)
  - secretKey: dbrootpassword
    remoteRef:
      key: dbrootpassword

  - secretKey: db-password
    remoteRef:
      key: db-password
  - secretKey: db-username
    remoteRef:
      key: db-username
  - secretKey: dbname
    remoteRef:
      key: dbname